#!/usr/bin/env python3
"""Generate catalog.toml from plugin manifests in child directories."""

from __future__ import annotations

import json
import sys
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "catalog.toml"
REQUIRED_FIELDS = ("id", "name", "plugin_api")
FIELD_ORDER = (
    "id",
    "name",
    "version",
    "author",
    "license",
    "icon",
    "description",
    "deprecated",
    "plugin_api",
    "tags",
    "dependencies",
)


def toml_value(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list) and all(isinstance(item, str) for item in value):
        return "[" + ", ".join(json.dumps(item, ensure_ascii=False) for item in value) + "]"
    raise TypeError(f"unsupported catalog value: {value!r}")


def load_manifests() -> list[tuple[Path, dict[str, object]]]:
    manifests: list[tuple[Path, dict[str, object]]] = []

    for path in sorted(ROOT.glob("*/plugin.toml")):
        with path.open("rb") as manifest_file:
            manifest = tomllib.load(manifest_file)

        missing = [field for field in REQUIRED_FIELDS if field not in manifest]
        if missing:
            fields = ", ".join(missing)
            raise ValueError(f"{path.relative_to(ROOT)}: missing required field(s): {fields}")

        plugin_api = manifest["plugin_api"]
        if not isinstance(plugin_api, int) or isinstance(plugin_api, bool) or plugin_api <= 0:
            raise ValueError(
                f"{path.relative_to(ROOT)}: plugin_api must be a positive integer"
            )

        manifests.append((path, manifest))

    if not manifests:
        raise ValueError("no child plugin.toml manifests found")

    return manifests


def render_catalog(manifests: list[tuple[Path, dict[str, object]]]) -> str:
    lines = [
        "# Generated by generate-catalog.py. Commit this file for Git source discovery.",
        "",
    ]

    for index, (path, manifest) in enumerate(manifests):
        if index:
            lines.append("")
        lines.append("[[plugin]]")
        for field in FIELD_ORDER:
            if field not in manifest:
                continue
            try:
                value = toml_value(manifest[field])
            except TypeError as error:
                raise TypeError(
                    f"{path.relative_to(ROOT)}: field {field}: {error}"
                ) from error
            lines.append(f"{field} = {value}")

    return "\n".join(lines) + "\n"


def main() -> int:
    try:
        catalog = render_catalog(load_manifests())
        OUTPUT.write_text(catalog, encoding="utf-8")
    except (OSError, tomllib.TOMLDecodeError, TypeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
