#!/usr/bin/env python3
"""Generate the committed Noctalia source catalog from plugin manifests."""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "catalog.toml"
REQUIRED_FIELDS = ("id", "name", "version", "author", "license", "description", "plugin_api")
FIELD_ORDER = (
    "id",
    "name",
    "version",
    "author",
    "license",
    "icon",
    "description",
    "deprecated",
    "plugin_api",
    "tags",
    "dependencies",
)


def toml_value(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list) and all(isinstance(item, str) for item in value):
        return "[" + ", ".join(json.dumps(item, ensure_ascii=False) for item in value) + "]"
    raise TypeError(f"unsupported catalog value: {value!r}")


def load_manifests() -> list[tuple[Path, dict[str, object]]]:
    manifests: list[tuple[Path, dict[str, object]]] = []
    for path in sorted(ROOT.glob("*/plugin.toml")):
        with path.open("rb") as manifest_file:
            manifest = tomllib.load(manifest_file)
        missing = [field for field in REQUIRED_FIELDS if field not in manifest]
        if missing:
            fields = ", ".join(missing)
            raise ValueError(f"{path.relative_to(ROOT)}: missing required field(s): {fields}")
        manifests.append((path, manifest))
    if not manifests:
        raise ValueError("no child plugin.toml manifests found")
    return manifests


def render_catalog(manifests: list[tuple[Path, dict[str, object]]]) -> str:
    lines = [
        "# Generated by .tools/generate-catalog.py. Commit this file for Git source discovery.",
        "",
    ]
    for index, (path, manifest) in enumerate(manifests):
        if index:
            lines.append("")
        lines.append("[[plugin]]")
        for field in FIELD_ORDER:
            if field not in manifest:
                continue
            try:
                value = toml_value(manifest[field])
            except TypeError as error:
                raise TypeError(
                    f"{path.relative_to(ROOT)}: field {field}: {error}"
                ) from error
            lines.append(f"{field} = {value}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when catalog.toml differs instead of rewriting it",
    )
    args = parser.parse_args()
    try:
        catalog = render_catalog(load_manifests())
        if args.check:
            current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
            if current != catalog:
                print(
                    "error: catalog.toml is stale; run ./.tools/generate-catalog.py",
                    file=sys.stderr,
                )
                return 1
            print("catalog.toml is current")
        else:
            OUTPUT.write_text(catalog, encoding="utf-8")
            print("generated catalog.toml")
    except (OSError, tomllib.TOMLDecodeError, TypeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

